name: flutterstudy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_boost:
#    git:
#      url: 'https://github.com/alibaba/flutter_boost.git'
#      ref: 'task/task_v1.12.13_support_hotfixes'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  english_words: ^3.1.0
#  fluttertoast: ^3.1.3
  flutter_screenutil: ^5.7.0

  #Json
  #json_annotation: ^3.0.0
  # 异常上报
  flutter_bugly: ^0.2.7
#  webview_flutter: 0.3.21

  # 腾讯云IM chat ui组件
  tencent_cloud_chat_uikit: 2.0.0-preview.6
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  #批量定义
    - assets/images/
    - assets/images/icon_pulltorefresh_arrow.png
  #单个定义如下：
  #  - images/title_back.png
  #  - images/icon_shop_info_edit.png
  #  - images/icon_shop_info_delete.png
  #  - images/icon_bg_credit_novip.png
  #  - images/icon_bg_credit_vip.png
  #  - images/iv_boy_user.png
  #  - images/icon_credit_setting.png
  #  - images/icon_bg_ranking.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
